### ISSUE TITLE
Error while run command "lerna run build"

### ISSUE THREAD

**Issue by Oustinger** [Byndyusoft/ui#62]
Вылетает ошибка при билде пакета `@byndyusoft-ui/use-hover`

log:
lerna ERR! npm run build exited 1 in '@byndyusoft-ui/use-hover'
lerna ERR! npm run build stdout:

> @byndyusoft-ui/use-hover@0.0.0 build
> tsc

src/useHover.ts(14,55): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'RefObject<T>' is not assignable to parameter of type 'Document | HTMLElement | Window | null | undefined'.
src/useHover.ts(15,55): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'RefObject<T>' is not assignable to parameter of type 'Document | HTMLElement | Window | null | undefined'.

lerna ERR! npm run build stderr:
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @byndyusoft-ui/use-hover@0.0.0
npm ERR!   at location: ...\ui\hooks\use-hover

lerna ERR! npm run build exited 1 in '@byndyusoft-ui/use-hover'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

**Comment by sadcitizen** [comment]
Это была проблема с конкретным хуком, я её исправил.
